DROP TABLE IF EXISTS USER_ADDRESSES;
DROP TABLE IF EXISTS ADDRESSES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ACTIVE BOOLEAN,
    USERNAME VARCHAR(30),
    EMAIL VARCHAR(30),
    LEVEL INTEGER,
    REGISTRATION_DATE DATE
);

CREATE TABLE ADDRESSES (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    STREET VARCHAR(30) NOT NULL,
    CITY VARCHAR(20) NOT NULL
);

CREATE TABLE USER_ADDRESSES (
    USER_ID INTEGER,
    ADDRESS_ID INTEGER,
    PRIMARY KEY (USER_ID, ADDRESS_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ID) ON DELETE CASCADE
);