server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CH16_SPRINGDATAREST?serverTimezone=UTC
    username: root
    password: abcd1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create